truck_booking/api/urls.py
from django.urls import include, path
from . import views
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from django.contrib.auth import views as auth_views
from api.views import registerUserView
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView


schema_view = get_schema_view(
   openapi.Info(
      title="Django Truck booking API",
      default_version='v1',
      description="Django Truck booking api documentation",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="macmanustephen@gmail.com"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)


urlpatterns = [

    path("api/user/register/", views.registerUserView.as_view(), name="register-user"),

    path("api/user/login", views.loginUserView.as_view(), name="login-user"),

    path("api/user/home", views.userHomeView.as_view(), name='home-view'),

    path("api/token", TokenObtainPairView.as_view(), name="get-token"),

    path("api/token/refresh", TokenRefreshView.as_view(), name="get-token"),

    path("api-auth/", include("rest_framework.urls")),   

    path('api/auth/password_reset/', auth_views.PasswordResetView.as_view(template_name = 'registration/password_reset_form.html'), name='password_reset'),

    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),

    path('api/auth/password_reset/confirm', auth_views.PasswordChangeView.as_view(), name='password_reset_confirm'),
    
    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    
    path('api/v1/swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),

    path("api/user/truck_config/add_truck/", views.registerTruckView.as_view(), name="register-truck"),

    path("api/user/truck_config/", views.viewAllTrucksView.as_view(), name='view-all-trucks'),

    path("api/user/truck_config/<str:pk>/edit", views.EditTruckView.as_view(), name='edit-truck'),

    path("api/user/truck_config/<str:pk>/delete", views.DeleteTruckView.as_view(), name='delete-truck'),

    path("api/user/truck_bookings/", views.TruckBookings.as_view(), name='booking-list'),

    path('api/user/truck_bookings/create/', views.registerTruckBookingView.as_view(), name='create-new-booking'),

    path("api/user/truck_bookings/<str:pk>/edit", views.EditTruckBookingView.as_view(), name='edit-truckbooking'),

    path("api/user/truck_bookings/<str:pk>/delete", views.DeleteTruckBookingView.as_view(), name='delete-truckbooking'),

]

    

truck_booking/calendarapp/urls.py
from django.urls import path

from . import views

app_name = "calendarapp"


urlpatterns = [
    
    path("api/user/calendar/", views.CalendarView.as_view(), name="calendar")
    
]

truck_booking/truck_booking/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('api.urls')),
    path("accounts/", include("django.contrib.auth.urls")),

    path('', include("calendarapp.urls")),
]

truck_booking/templates/base.html
<!-- cal/templates/cal/base.html -->

{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/calender.css' %}">
  <title>Django Calendar App</title>
</head>
<body>

  {% block content %}

  {% endblock %}

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>

  {% block script %}
  {% endblock %}
</body>
</html>

truck_booking/templates/calendar.html
{% extends 'base.html' %}

{% block content %}
<div class="clearfix">
    <span class="left m-2" style="font-size: 20px;">Wellcome, {{ request.user }}</span>
    <a class="btn btn-info right mr-2" href="{% url 'calendarapp:calendar' %}?{{ next_month }} "> Next Month >> </a>
    <a class="btn btn-info right mr-2" href="{% url 'calendarapp:calendar' %}?{{ prev_month }}"> << Previous Month </a>
    
</div>
<div style="color: blueviolet;">
    {{ calendar }}
</div>
{% endblock %}

truck_booking/templates/home.html
<!DOCTYPE html>
<html>
<head>
<title>Truck Booking</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body,h1 {font-family: "Raleway", Arial, sans-serif}
h1 {letter-spacing: 6px}
.w3-row-padding img {margin-bottom: 12px}
</style>
</head>
<body>

<!-- !PAGE CONTENT! -->
<div class="home-content" style="max-width:1500px">

<!-- Header -->
<header class="w3-panel w3-center w3-opacity" style="padding:128px 16px">
  <h1 class="w3-xlarge">Welcome</h1>
  <h1> User </h1>
  
  <div class="w3-padding-32">
    <div class="w3-bar w3-border">
      <a href="#" class="w3-bar-item w3-button">Truck</a>
      
      <a href="#" class="w3-bar-item w3-button w3-light-grey">Test Bench</a>
      
    </div>
  </div>

</header>

<!-- Photo Grid -->
<div class="w3-row-padding w3-grayscale" style="margin-bottom:128px">
  <div class="w3-half">
    
</div>

  <div class="w3-half">
    
  </div>

</div>
  
<!-- End Page Content -->
</div>

<!-- Footer -->
<footer class="w3-container w3-padding-64 w3-light-grey w3-center w3-large"> 
  <i class="fa fa-facebook-official w3-hover-opacity"></i>
  <i class="fa fa-instagram w3-hover-opacity"></i>
  <i class="fa fa-snapchat w3-hover-opacity"></i>
  <i class="fa fa-pinterest-p w3-hover-opacity"></i>
  <i class="fa fa-twitter w3-hover-opacity"></i>
  <i class="fa fa-linkedin w3-hover-opacity"></i>
  <p>Powered by <a href="https://www.w3schools.com/w3css/default.asp" target="_blank" class="w3-hover-text-green">w3.css</a></p>
</footer>

</body>
</html>